# Site settings
title: Shakhrizoda Bobojonova
description: Backend Developer | Python
baseurl: "" # leave empty for root
url: "https://sshariaa.github.io" # replace <your-username> with your GitHub username

# Theme settings
theme: minimal
