

title: Shakhrizoda Bobojonova
description: Backend Developer | Python
author: Shakhrizoda
theme: jekyll-theme-cayman
url: "https://sshariaa.github.io"


github_username: sshariaa.100
email: sshariaa.1008@gmail.com

